import os


path_to_tables = "/src/tables/"
vco_file_name = "phasors.h"
lfo_env_file_name = "slow_phasors.h"

vco_file_header = """// autogenerated by scripts/generate_phasors.py
// do not modify!!
#include<Arduino.h>
#ifndef PHASORS_TABLE_H
#define PHASORS_TABLE_H
"""

def main():
    vco_file_path = f"{os.getcwd()}{path_to_tables}{vco_file_name}"
    lfo_env_file_path  = f"{os.getcwd()}{path_to_tables}{lfo_env_file_name}"
    

if __name__ == "__main__":
    main()